spring:
  datasource:
    url: ${MYSQL_DATABASE_URL}
    username: ${MYSQL_DATABASE_USERNAME}
    password: ${MYSQL_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate

  data:
    redis:
      cluster:
        nodes: ${REDIS_CLUSTER_NODES}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_SNS_ACCESS_KEY}
        secret-key: ${AWS_SNS_SECRET_KEY}
      region:
        static: ${AWS_SNS_REGION}
      sns:
        arn: ${AWS_SNS_ARN}
      s3:
        bucket: ${AWS_S3_BUCKET}
jwt:
  access-secret-key: ${JWT_ACCESS_SECRET_KEY}
  access-expire-second: ${JWT_ACCESS_EXPIRE_LENGTH}
  refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}
  refresh-expire-second: ${JWT_REFRESH_EXPIRE_LENGTH}

logging:
  slack:
    webhook-uri: ${SLACK_ERROR_URL}
  config: classpath:logback-spring.xml
