spring:
  data:
    redis:
      host: localhost
      port: 6379

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5
jwt:
  access-secret-key: "asfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfasdfadfasdfasdfasdfa"
  access-expire-second: 1000000
  refresh-secret-key: "assfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfasdfadfasdfasdfasdfa"
  refresh-expire-second: 1000000
