server:
  servlet:
    context-path: /api

firebase:
  secret: ${FIREBASE_SECRET}

auth:
  filter:
    exclusions: auth, auth/access
multipart:
  profile-image:
    allow-file-type: png,jpg,jpeg
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: test
