spring:
  data:
    redis:
      host: localhost


de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5
    redis:
      embedded:
        version: 3.2.1


jwt:
  access-secret-key: "asfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfasdfadfasdfasdfasdfa"
  access-expire-second: 1000000
  refresh-secret-key: "assfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfasdfadfasdfasdfasdfa"
  refresh-expire-second: 1000000