spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  data:
    redis:
      url: ${REDIS_URL}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_SNS_ACCESS_KEY}
        secret-key: ${AWS_SNS_SECRET_KEY}
      region:
        static: ${AWS_SNS_REGION}
      sns:
        arn: ${AWS_SNS_ARN}
      s3:
        bucket: ${AWS_S3_BUCKET}
        image-directory: ${AWS_S3_IMAGE_DIRECTORY}

jwt:
  access-secret-key: ${JWT_ACCESS_SECRET_KEY}
  access-expire-second: ${JWT_ACCESS_EXPIRE_LENGTH}
  refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}
  refresh-expire-second: ${JWT_REFRESH_EXPIRE_LENGTH}