spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/webflux?authSource=admin&authMechanism=SCRAM-SHA-1
    redis:
      host: localhost


  mongodb:
    embedded:
      version: 3.5.5

jwt:
  access-secret-key: "asfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfasdfadfasdfasdfasdfa"
  access-expire-second: 1000000
  refresh-secret-key: "assfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfasdfadfasdfasdfasdfa"
  refresh-expire-second: 1000000