server:
  servlet:
    context-path: /api
spring:
  data:
    redis:
      host: localhost
      port: 6379

firebase:
  secret: ${FIREBASE_SECRET}

auth:
  filter:
    exclusions: "auth"

jwt:
  access-secret-key: "asfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasd"
  access-expire-second: 1000000
  refresh-secret-key: "assfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasads"
  refresh-expire-second: 2000000
---
spring:
  config:
    activate:
      on-profile: local, dev, prd

  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_DATABASE}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      authentication-database: ${DB_AUTH_SOURCE}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}

jwt:
  access-secret-key: ${JWT_ACCESS_SECRET_KEY}
  access-expire-second: ${JWT_ACCESS_EXPIRE_LENGTH}
  refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}
  refresh-expire-second: ${JWT_REFRESH_EXPIRE_LENGTH}
